//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nmfs.Agepro.CoreLib.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class agepro_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal agepro_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nmfs.Agepro.CoreLib.resources.agepro_strings", typeof(agepro_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HARVEST].
        /// </summary>
        internal static string HarvestScenario_INP_Header {
            get {
                return ResourceManager.GetString("HarvestScenario_INP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Scenario.
        /// </summary>
        internal static string HarvestScenario_Text {
            get {
                return ResourceManager.GetString("HarvestScenario_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-MULT.
        /// </summary>
        internal static string HarvestSpec_Case0 {
            get {
                return ResourceManager.GetString("HarvestSpec_Case0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDINGS.
        /// </summary>
        internal static string HarvestSpec_Case1 {
            get {
                return ResourceManager.GetString("HarvestSpec_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVALS.
        /// </summary>
        internal static string HarvestSpec_Case2 {
            get {
                return ResourceManager.GetString("HarvestSpec_Case2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Spec.
        /// </summary>
        internal static string HarvestTable_Col_Spec {
            get {
                return ResourceManager.GetString("HarvestTable_Col_Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARVEST VALUE.
        /// </summary>
        internal static string HarvestTable_Col_Value {
            get {
                return ResourceManager.GetString("HarvestTable_Col_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLEET-.
        /// </summary>
        internal static string HarvestTable_Col_ValueFleetSuffix {
            get {
                return ResourceManager.GetString("HarvestTable_Col_ValueFleetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGEPRO.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Star Levels must be in ascending order.
        /// </summary>
        internal static string PStar_Error_DecendingLevels {
            get {
                return ResourceManager.GetString("PStar_Error_DecendingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing overfishing value..
        /// </summary>
        internal static string PStar_Error_InvalidF {
            get {
                return ResourceManager.GetString("PStar_Error_InvalidF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing number of P-Star Levels..
        /// </summary>
        internal static string PStar_Error_InvalidLevels {
            get {
                return ResourceManager.GetString("PStar_Error_InvalidLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid P-Star Year Specification..
        /// </summary>
        internal static string PStar_Error_InvalidYear {
            get {
                return ResourceManager.GetString("PStar_Error_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Star Data Table Has more than one row.
        /// </summary>
        internal static string PStar_Error_RowCount {
            get {
                return ResourceManager.GetString("PStar_Error_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSTAR].
        /// </summary>
        internal static string PStar_INP_Header {
            get {
                return ResourceManager.GetString("PStar_INP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pstar.
        /// </summary>
        internal static string PStar_Text {
            get {
                return ResourceManager.GetString("PStar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing rebuilder confidence level.
        /// </summary>
        internal static string Rebuilder_Error_InvaildConf {
            get {
                return ResourceManager.GetString("Rebuilder_Error_InvaildConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing rebuilder target value..
        /// </summary>
        internal static string Rebuilder_Error_InvalidTarget {
            get {
                return ResourceManager.GetString("Rebuilder_Error_InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Rebuilder Year Specification..
        /// </summary>
        internal static string Rebuilder_Error_InvalidYear {
            get {
                return ResourceManager.GetString("Rebuilder_Error_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilder.
        /// </summary>
        internal static string Rebuilder_Text {
            get {
                return ResourceManager.GetString("Rebuilder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REBUILD].
        /// </summary>
        internal static string Rebulider_INP_Header {
            get {
                return ResourceManager.GetString("Rebulider_INP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Recruitment_Default_Int {
            get {
                return ResourceManager.GetString("Recruitment_Default_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.000.
        /// </summary>
        internal static string Recruitment_Default_Value {
            get {
                return ResourceManager.GetString("Recruitment_Default_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Recruitment Model Number {0}.
        /// </summary>
        internal static string Recruitment_Error_InvaildCase {
            get {
                return ResourceManager.GetString("Recruitment_Error_InvaildCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RECRUIT].
        /// </summary>
        internal static string Recruitment_INP_Header {
            get {
                return ResourceManager.GetString("Recruitment_INP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string Recruitment_Max_Obs {
            get {
                return ResourceManager.GetString("Recruitment_Max_Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Recruitment Data ....
        /// </summary>
        internal static string Recruitment_ReadLine {
            get {
                return ResourceManager.GetString("Recruitment_ReadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Recruit Models does not match input file recruitModel count.
        /// </summary>
        internal static string Recruitment_ReadLine_Error_NumRecruitModel {
            get {
                return ResourceManager.GetString("Recruitment_ReadLine_Error_NumRecruitModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Recuitment Model Data ....
        /// </summary>
        internal static string Recruitment_ReadLine_Model {
            get {
                return ResourceManager.GetString("Recruitment_ReadLine_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        internal static string Recruitment_Text {
            get {
                return ResourceManager.GetString("Recruitment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection {0}.
        /// </summary>
        internal static string RecruitProb_ColName {
            get {
                return ResourceManager.GetString("RecruitProb_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At row {0} of recruitment probablity:
        ///{1}{2}.
        /// </summary>
        internal static string RecruitProb_Error_InvaildProb {
            get {
                return ResourceManager.GetString("RecruitProb_Error_InvaildProb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment probablity sum does not equal 1.0: Probability sum is {0}.
        /// </summary>
        internal static string RecruitProb_Error_InvalidSum {
            get {
                return ResourceManager.GetString("RecruitProb_Error_InvalidSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Probability.
        /// </summary>
        internal static string RecruitProb_Name {
            get {
                return ResourceManager.GetString("RecruitProb_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Task_Complete {
            get {
                return ResourceManager.GetString("Task_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
