//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nmfs.Agepro.CoreLib.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class agepro_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal agepro_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nmfs.Agepro.CoreLib.resources.agepro_strings", typeof(agepro_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HARVEST].
        /// </summary>
        internal static string HarvestScenario_INP_header {
            get {
                return ResourceManager.GetString("HarvestScenario_INP_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Scenario.
        /// </summary>
        internal static string HarvestScenario_text {
            get {
                return ResourceManager.GetString("HarvestScenario_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-MULT.
        /// </summary>
        internal static string HarvestSpec_case0 {
            get {
                return ResourceManager.GetString("HarvestSpec_case0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDINGS.
        /// </summary>
        internal static string HarvestSpec_case1 {
            get {
                return ResourceManager.GetString("HarvestSpec_case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVALS.
        /// </summary>
        internal static string HarvestSpec_case2 {
            get {
                return ResourceManager.GetString("HarvestSpec_case2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Spec.
        /// </summary>
        internal static string HarvestTable_col_spec {
            get {
                return ResourceManager.GetString("HarvestTable_col_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARVEST VALUE.
        /// </summary>
        internal static string HarvestTable_col_value {
            get {
                return ResourceManager.GetString("HarvestTable_col_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLEET-.
        /// </summary>
        internal static string HarvestTable_col_valueFleetSuffix {
            get {
                return ResourceManager.GetString("HarvestTable_col_valueFleetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGEPRO.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Star Levels must be in ascending order.
        /// </summary>
        internal static string Pstar_error_decendingLevels {
            get {
                return ResourceManager.GetString("Pstar_error_decendingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing overfishing value..
        /// </summary>
        internal static string PStar_error_invalidF {
            get {
                return ResourceManager.GetString("PStar_error_invalidF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing number of P-Star Levels..
        /// </summary>
        internal static string PStar_error_invalidLevels {
            get {
                return ResourceManager.GetString("PStar_error_invalidLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid P-Star Year Specification..
        /// </summary>
        internal static string PStar_error_invalidYear {
            get {
                return ResourceManager.GetString("PStar_error_invalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Star Data Table Has more than one row.
        /// </summary>
        internal static string Pstar_error_rowCount {
            get {
                return ResourceManager.GetString("Pstar_error_rowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSTAR].
        /// </summary>
        internal static string Pstar_INP_header {
            get {
                return ResourceManager.GetString("Pstar_INP_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pstar.
        /// </summary>
        internal static string Pstar_text {
            get {
                return ResourceManager.GetString("Pstar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing rebuilder confidence level.
        /// </summary>
        internal static string Rebuilder_error_invaildConf {
            get {
                return ResourceManager.GetString("Rebuilder_error_invaildConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing rebuilder target value..
        /// </summary>
        internal static string Rebuilder_error_invalidTarget {
            get {
                return ResourceManager.GetString("Rebuilder_error_invalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Rebuilder Year Specification..
        /// </summary>
        internal static string Rebuilder_error_invalidYear {
            get {
                return ResourceManager.GetString("Rebuilder_error_invalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilder.
        /// </summary>
        internal static string Rebuilder_text {
            get {
                return ResourceManager.GetString("Rebuilder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REBUILD].
        /// </summary>
        internal static string Rebulider_INP_header {
            get {
                return ResourceManager.GetString("Rebulider_INP_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0}.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
